### PR TITLE
III: Fix the missing window icon

### LINKED ISSUE #117: III: The window icon is incorrect
This is a placeholder issue for a MR

### PR DESCRIPTION
**Pull request by TheComputerGuy96**
For some reason GTA 3 sets the hIcon value in WNDCLASSA struct to NULL which causes the window icon to be the default one (this was fixed in Vice City)

Fixes #117

### CODE REVIEW

**Comment by CookiePLMonster** [comment]
Please don't add new fixes using addresses. Use patterns.

**Comment by TheComputerGuy96** [comment]
Hopefully this pattern is good enough

File: SilentPatch/Common_ddraw.cpp [hunk 1]
```diff
@@ -229,6 +231,14 @@ namespace Common {
 			}
 			TXN_CATCH();
 
+			// III: Patch the icon handle to fix missing window icon
+			// (This is fixed since VC)
+			try
+			{
+				auto addr = get_pattern("c7 44 24 1c 00 00 00 00 c7 44 24 08 00 20 00", 0x4);
+				Patch<HICON>(addr, wndIconIII);
```
Comment (CookiePLMonster) [inline SilentPatch/Common_ddraw.cpp]:
```suggestion
				auto addr = get_pattern("c7 44 24 1c 00 00 00 00 c7 44 24 08 00 20 00", 0x4);
				
				HICON wndIconIII = LoadIcon(GetModuleHandle(nullptr), MAKEINTRESOURCE(0x412)); // Group icon ID
				Patch<HICON>(addr, wndIconIII);
```

Since you are writing a handle directly and not a pointer to it, loading the icon in advance is pointless. If you load it here, it also won't load needlessly in Vice City.

**Comment by CookiePLMonster** [comment]
> Hopefully this pattern is good enough

The pattern looks good, yeah. Added just one extra comment.

Also can you add it to https://github.com/CookiePLMonster/SilentPatch/blob/dev/CHANGELOG-III.md in "Other fixes", just above the configurable ones?

File: SilentPatch/Common_ddraw.cpp (hunk 1 above)
Comment (TheComputerGuy96) [reply SilentPatch/Common_ddraw.cpp]: That variable was needed there for the non-pattern version (to prevent duplication) and I rushed the pattern-based fix

Anyway that should be fixed now

**Comment by CookiePLMonster** [comment]
Verified working fine in III and failing the pattern match gracefully in VC. Thanks!

I also realized why I never noticed it myself - the windowed mode from UAL adds this icon automatically by itself.
